apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main.rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
  - name: name.rules
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
      for: 2m
      labels:
        severity: "warning"
        namespace: monitoring
      annotations:
        summary:  "50% alert on Host CPU"
        description: "CPU Load on host is over 50%\n value = {{ $value }}\n Instance = {{ $labels.instance }}"
    - alert: KubernetesPodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        description: "Pod = {{ $labels.pod }} is crash looping\n Value = {{ $value }}"
        summary: "Kubernetes Pod Crash Looping"

