apiVersion: monitoring.coreos.com/v1beta1
kind: AlertManagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  receivers:
  - name: 'personal-email'
    emailConfigs:
    - to: "user@gmail.com"
      from: "user@gmail.com"
      smarthost: "smtp.gmail.com:587"
      authUsername: "user@gmail.com"
      authIdentity: "user@gmail.com"
      authPassword:
        name: gmail-auth
        key: password
