apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-metrics
  namespace: microservices
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: app-service
      app.kubernetes.io/name: app-service

  namespaceSelector:
    matchNames:
      - microservices

  endpoints:
    - port: http
      path: /metrics
      interval: 15s