apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        args:
          - --redis.addr=redis://redis-master.microservices.svc.cluster.local:6379
          - --redis.password=change-me-secure-password
        ports:
        - containerPort: 9121
